Задание 6. Добавлена функциональность регистрации пользователя
gpb-it-factory/semkin-middle-service pull request #2
Opened 2024-06-02 17:50 UTC by vnsemkin

2024-06-04 05:34 UTC, DirtyRamirez commented on src/main/java/org/vnsemkin/semkinmiddleservice/application/dtos/front/FrontReqDto.java
> +        return name.matches(NAME_REGEX) && name.length() <= 10;
цифры типа 10 и 50 лучше вынести в конфиг файл и от туда получать

2024-06-04 05:35 UTC, DirtyRamirez commented on src/main/java/org/vnsemkin/semkinmiddleservice/application/usecases/CustomerRegistrationService.java
> +        } else {
else лишнее

2024-06-04 05:35 UTC, DirtyRamirez commented on src/main/java/org/vnsemkin/semkinmiddleservice/presentation/web_client/BackendClientInterfaceImp.java
> +                } else {
else лишнее

2024-06-04 05:35 UTC, DirtyRamirez commented on src/main/java/org/vnsemkin/semkinmiddleservice/presentation/web_client/BackendClientInterfaceImp.java
> +                } else {
лишнее)

2024-06-04 06:01 UTC, DirtyRamirez requested changes
чуть поправиь плз

2024-06-05 03:49 UTC, DirtyRamirez commented on src/main/java/org/vnsemkin/semkinmiddleservice/application/config/AppConstants.java
> +    public static final int INT_TEN = 10;
Ну тут надо не просто создать переменные, а чтобы они были осмысленные. Там у тебя происходит валидация, так что было бы логично сделать что-то вроде MAX_NAME_LENGTH или вроде того

2024-06-05 05:24 UTC, vnsemkin commented on src/main/java/org/vnsemkin/semkinmiddleservice/application/config/AppConstants.java
> +    public static final int INT_TEN = 10;
Понял. Сделаем. Спасибо.

2024-06-06 06:07 UTC, DirtyRamirez approved these changes
ship it!)

2024-06-06 11:15 UTC, merged